const { DatabaseAPI, DatabaseConnection } = require('../services/db');
const { getMaxIterations } = require('../utils/maxIterations');

const REPORT_SECTION_CONFIG = [
  { key: 'summary', heading: '## Summary' },
  { key: 'workPerformed', heading: '## Work Performed' },
  { key: 'outstanding', heading: '## Outstanding / Risks' },
  { key: 'handoff', heading: '## Handoff Notes' }
];

const REPORT_SECTION_TITLES = REPORT_SECTION_CONFIG.reduce((acc, cfg) => {
  acc[cfg.key] = cfg.heading.replace(/^##\s+/, '');
  return acc;
}, {});

const REPORT_SECTION_ALIASES = {
  summary: ['summary', 'resumo', 'overview'],
  workPerformed: ['work performed', 'done', 'execution', 'work log', 'analysis'],
  outstanding: ['outstanding / risks', 'outstanding risks', 'outstanding', 'risks', 'remaining', 'open items', 'todo'],
  handoff: ['handoff notes', 'handoff', 'next steps', 'continuation', 'follow up', 'follow-up']
};

function normalizeHeadingKey(title) {
  return (title || '')
    .toString()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function mapHeadingToSectionKey(title) {
  const normalized = normalizeHeadingKey(title);
  if (!normalized) return null;
  for (const [key, aliases] of Object.entries(REPORT_SECTION_ALIASES)) {
    if (aliases.includes(normalized)) return key;
  }
  return null;
}

function parseMarkdownSections(markdown) {
  const lines = (markdown || '').split(/\r?\n/);
  const sections = [];
  let current = null;
  for (const line of lines) {
    const headingMatch = line.match(/^##\s+(.+)/i);
    if (headingMatch) {
      if (current) {
        current.content = current.content.join('\n').trim();
        sections.push(current);
      }
      current = {
        rawHeading: headingMatch[1].trim(),
        content: []
      };
    } else {
      if (!current) {
        current = { rawHeading: '__preamble__', content: [] };
      }
      current.content.push(line);
    }
  }
  if (current) {
    current.content = current.content.join('\n').trim();
    sections.push(current);
  }

  let preamble = '';
  const mapped = sections
    .filter(section => {
      if (section.rawHeading === '__preamble__') {
        if (section.content) preamble = section.content.trim();
        return false;
      }
      return true;
    })
    .map(section => ({
      heading: section.rawHeading,
      key: mapHeadingToSectionKey(section.rawHeading),
      content: section.content || ''
    }));

  return { preamble, sections: mapped };
}

function ensureContent(value, fallback) {
  const trimmed = (value || '').toString().trim();
  return trimmed.length > 0 ? trimmed : fallback;
}

function formatBlockQuote(text) {
  if (!text) return '';
  return text
    .split(/\r?\n/)
    .map(line => line.trim().length === 0 ? '>' : `> ${line}`)
    .join('\n');
}

function buildStructuredReport(sections, { heading = '# Focus Report', completed = true, autogenerated = false } = {}) {
  const normalizedSections = {};
  const fallbackUsage = {};

  const summaryValue = (sections.summary || '').toString().trim();
  if (summaryValue.length === 0) {
    fallbackUsage.summary = true;
    normalizedSections.summary = completed
      ? '- No summary provided.'
      : '- Focus incomplete. No summary provided.';
  } else {
    fallbackUsage.summary = false;
    normalizedSections.summary = summaryValue;
  }

  const workValue = (sections.workPerformed || '').toString().trim();
  if (workValue.length === 0) {
    fallbackUsage.workPerformed = true;
    normalizedSections.workPerformed = '- No work recorded.';
  } else {
    fallbackUsage.workPerformed = false;
    normalizedSections.workPerformed = workValue;
  }

  const outstandingValue = (sections.outstanding || '').toString().trim();
  if (outstandingValue.length === 0) {
    fallbackUsage.outstanding = true;
    normalizedSections.outstanding = completed ? '- None reported.' : '- Outstanding items not documented.';
  } else {
    fallbackUsage.outstanding = false;
    normalizedSections.outstanding = outstandingValue;
  }

  const handoffValue = (sections.handoff || '').toString().trim();
  if (handoffValue.length === 0) {
    fallbackUsage.handoff = true;
    normalizedSections.handoff = '- Awaiting coordinator decision.';
  } else {
    fallbackUsage.handoff = false;
    normalizedSections.handoff = handoffValue;
  }

  const lines = [heading.trim()];
  if (autogenerated) {
    lines.push('', '> _Auto-generated because the focus failed to submit a report._');
  }

  for (const config of REPORT_SECTION_CONFIG) {
    lines.push('', config.heading);
    lines.push(normalizedSections[config.key]);
  }

  if (typeof completed === 'boolean') {
    lines.push('', `**Completed:** ${completed ? '✅ Yes' : '❌ No'}`);
  }

  return { markdown: lines.join('\n'), sections: normalizedSections, fallbackUsage };
}

function buildCoordinatorSummary({ focusGoal = {}, sections = null, completed = true, iterationsInfo = null }) {
  const sectionData = sections || {};

  const contextBullets = [];
  if (focusGoal.goal) contextBullets.push(`- Objective: ${focusGoal.goal}`);
  if (focusGoal.firstStep) contextBullets.push(`- First Critical Step: ${focusGoal.firstStep}`);
  if (focusGoal.minimumDeliverable) contextBullets.push(`- Minimal Deliverable: ${focusGoal.minimumDeliverable}`);
  if (focusGoal.guardrails) contextBullets.push(`- Guardrails: ${focusGoal.guardrails}`);

  const contextBlocks = [];
  if (focusGoal.context) contextBlocks.push(focusGoal.context.trim());
  if (contextBullets.length > 0) contextBlocks.push(contextBullets.join('\n'));
  const globalContext = contextBlocks.length > 0 ? contextBlocks.join('\n\n') : '(No additional context provided.)';

  const estadoAtual = ensureContent(sectionData.summary, completed
    ? '- Focus completed but summary was empty.'
    : '- Focus incomplete and summary missing. Review outstanding items.');
  const riscos = ensureContent(sectionData.outstanding, completed
    ? '- None reported.'
    : '- Outstanding items require follow-up.');
  const opcoes = ensureContent(sectionData.handoff, '- Coordinator must choose the next action based on context and risks.');

  const lines = [
    '# Coordinator Summary',
    '',
    '## Global Context',
    globalContext,
    '',
    '## Estado Atual',
    estadoAtual,
    '',
    '## Riscos / Bloqueios',
    riscos,
    '',
    '## Continuation Options',
    opcoes
  ];

  if (iterationsInfo && iterationsInfo.initial != null) {
    const percent = iterationsInfo.initial > 0
      ? Math.round((iterationsInfo.consumed / iterationsInfo.initial) * 100)
      : 0;
    lines.push('', '## Efficiency', `- ${iterationsInfo.consumed} / ${iterationsInfo.initial} iterations consumed (${percent}%)`);
  }

  return lines.join('\n');
}

function normalizeFocusReport(rawReport, { focusGoal = null, completed = true, heading }) {
  const parsed = parseMarkdownSections(rawReport);
  const normalized = {
    summary: parsed.preamble || '',
    workPerformed: '',
    outstanding: '',
    handoff: ''
  };

  for (const section of parsed.sections) {
    const content = section.content || '';
    const key = section.key;
    if (key && !normalized[key]) {
      normalized[key] = content.trim();
    }
  }

  // Backwards compatibility: map old headings appearing as content lines
  if (!normalized.workPerformed) {
    const doneSection = parsed.sections.find(sec => normalizeHeadingKey(sec.heading) === 'done');
    if (doneSection) normalized.workPerformed = doneSection.content;
  }
  if (!normalized.outstanding) {
    const remainingSection = parsed.sections.find(sec => ['remaining', 'remaining work'].includes(normalizeHeadingKey(sec.heading)));
    if (remainingSection) normalized.outstanding = remainingSection.content;
  }
  if (!normalized.handoff) {
    const nextSection = parsed.sections.find(sec => ['next steps', 'next step'].includes(normalizeHeadingKey(sec.heading)));
    if (nextSection) normalized.handoff = nextSection.content;
  }

  // Fallbacks informed by focus goal
  if (!normalized.summary && focusGoal) {
    normalized.summary = focusGoal.minimumDeliverable
      ? `Target deliverable: ${focusGoal.minimumDeliverable}`
      : (focusGoal.goal || 'Focus summary unavailable.');
  }

  if (!normalized.outstanding && !completed && focusGoal) {
    normalized.outstanding = `- Unable to complete: ${focusGoal.goal || 'Goal not specified.'}`;
  }

  if (!normalized.handoff) {
    normalized.handoff = '- Coordinator must decide the next focus based on outstanding items.';
  }

  const result = buildStructuredReport(normalized, {
    heading: heading || '# Focus Report',
    completed,
    autogenerated: false
  });

  const warnings = [];
  if (result.fallbackUsage) {
    for (const [key, usedFallback] of Object.entries(result.fallbackUsage)) {
      if (usedFallback) {
        const sectionTitle = REPORT_SECTION_TITLES[key] || key;
        warnings.push(`Section "${sectionTitle}" was missing and a fallback entry was inserted.`);
      }
    }
  }

  return { ...result, normalized: true, warnings };
}

async function sendReportToParent({ conversationId, report, sections = null, completed = true, autogenerated = false, db, warnings = [], notifyParent = true }) {
  const currentConv = db.getConversation(conversationId);
  if (!currentConv || currentConv.conversation_type !== 'focus') {
    return { error: 'Not a focus conversation' };
  }

  const parentId = currentConv.parent_id;
  if (!parentId) {
    return { error: 'Focus has no parent conversation' };
  }

  let focusGoal = {};
  try {
    focusGoal = currentConv.focus_goal ? JSON.parse(currentConv.focus_goal) : {};
  } catch (_) {
    focusGoal = {};
  }

  // Iteration accounting: how many iterations the focus consumed
  const initialIterations = Number(focusGoal.initialMaxIterations) || null;
  const finalIterations = Number(currentConv.max_iterations) || 0;
  const iterationsInfo = initialIterations != null
    ? {
        initial: initialIterations,
        remaining: Math.max(0, finalIterations),
        consumed: Math.max(0, initialIterations - finalIterations),
      }
    : null;

  const coordinatorSummary = buildCoordinatorSummary({
    focusGoal,
    sections,
    completed,
    iterationsInfo
  });

  const reportWithMeta = {
    schemaVersion: '2026-06-01',
    report,
    sections: sections || null,
    coordinatorSummary,
    focusId: conversationId,
    focusTitle: currentConv.title,
    completed,
    autogenerated,
    warnings,
    iterations: iterationsInfo,
    reportedAt: new Date().toISOString()
  };

  const reportJson = JSON.stringify(reportWithMeta);

  // 1. Actualizar focus_report na BD
  db.updateFocusReport(conversationId, reportJson);

  // 2. Criar a mensagem de report no focus filho via stateChange
  //    (stateChange handles: create message, broadcast, state transition)
  try {
    const cm = require('../services/serviceFactory').getConversationManager();
    cm.stateChange(currentConv, {
      conversation_id: conversationId,
      role: 'assistant',
      content: report,
      status: 'completed',
      _focusReport: true
    });
  } catch (e) {
    console.error('[sendReportToParent] Failed to create report message via stateChange:', e);
    // Fallback: direct DB call
    try {
      db.createMessage({
        conversation_id: conversationId,
        role: 'assistant',
        content: report,
        status: 'completed'
      });
    } catch (_) {}
  }

  // 3. Limpeza de active_focus
  db.clearActiveFocus(parentId);
  let ancestorId = parentId;
  while (ancestorId) {
    const ancestor = db.getConversation(ancestorId);
    if (!ancestor) break;
    if (ancestor.active_focus_id === currentConv.id || ancestor.active_focus_id === conversationId || ancestor.active_focus_id === parentId) {
      db.clearActiveFocus(ancestor.id);
    }
    ancestorId = ancestor.parent_id;
  }

  if (currentConv.focus_goal) {
    try {
      const goalData = JSON.parse(currentConv.focus_goal);
      if (goalData.finalizing) {
        goalData.finalizing = false;
        goalData.finalizedAt = new Date().toISOString();
        db.updateFocusGoal(conversationId, JSON.stringify(goalData));
      }
    } catch (_) {}
  }

  // 4. Update the existing createFocus tool message with the final report
  const createFocusMsg = db.findCreateFocusToolMessage(parentId, conversationId);
  if (createFocusMsg) {
    const updatedToolResult = JSON.stringify({
      focusId: conversationId,
      parentConversationId: parentId,
      title: currentConv.title,
      status: completed ? 'completed' : 'partial',
      report: reportWithMeta,
      coordinatorSummary,
      completed,
      sections: sections || null
    });
    db.updateMessage(createFocusMsg.id, {
      tool_result: updatedToolResult,
      status: 'completed'
    });
    const updatedMsg = db.getMessage(createFocusMsg.id);
    try {
      const socketService = require('../services/socketService');
      socketService.broadcastToConversation(parentId, 'message', updatedMsg);
    } catch (_) {}
  }

  // 5. Broadcast focus events (specific to the focus system)
  try {
    const socketService = require('../services/socketService');
    socketService.broadcastToConversation(parentId, 'focus_report', {
      focusId: conversationId,
      parentConversationId: parentId,
      title: currentConv.title,
      report: reportJson,
      status: completed ? 'completed' : 'partial'
    });
    socketService.broadcastToConversation(parentId, 'focus_closed', {
      focusId: conversationId,
      parentConversationId: parentId,
      title: currentConv.title,
      status: completed ? 'completed' : 'partial',
      report: reportJson,
      coordinatorSummary
    });
  } catch (_) {}

  // 6. Notify parent conversation (if necessary)
  if (notifyParent) {
    const reportContent = [
      `Investigation report received from "${currentConv.title}".`,
      `Completed: ${completed ? 'Yes' : 'No'}.`,
      '',
      coordinatorSummary,
      '',
      '---',
      '',
      '## Full Investigation Report',
      report,
      '',
      '---',
      '',
      'Decision required: create a new investigation, request clarification, or conclude the parent conversation based on this report.'
    ].join('\n');

    // Usar handleUserMessage que passa por stateChange
    try {
      const cm = require('../services/serviceFactory').getConversationManager();
      cm.handleUserMessage(
        { content: reportContent },
        parentId,
        null
      );
    } catch (e) {
      console.error('[sendReportToParent] Failed to create parent notification via handleUserMessage:', e);
      // Fallback: direct DB call
      try {
        db.createMessage({
          conversation_id: parentId,
          role: 'user',
          content: reportContent,
          status: 'completed'
        });
        db.markConversationAsQueued(parentId);
      } catch (_) {}
    }
  }

  // 7. Broadcast a todos os ancestrais
  let rootConv = currentConv;
  try {
    const socketService = require('../services/socketService');
    while (rootConv.parent_id) {
      const p = db.getConversation(rootConv.parent_id);
      if (!p) break;
      rootConv = p;
    }

    socketService.broadcastToConversation(parentId, 'focus_status_change', {
      focusId: conversationId,
      parentConversationId: parentId,
      status: completed ? 'completed' : 'partial',
      report: reportJson
    });

    if (rootConv.id !== parentId) {
      socketService.broadcastToConversation(rootConv.id, 'focus_status_change', {
        focusId: conversationId,
        parentConversationId: rootConv.id,
        status: completed ? 'completed' : 'partial',
        report: reportJson
      });
      socketService.broadcastToConversation(rootConv.id, 'focus_closed', {
        focusId: conversationId,
        parentConversationId: rootConv.id,
        title: currentConv.title,
        status: completed ? 'completed' : 'partial',
        report: reportJson,
        coordinatorSummary
      });
    }
  } catch (_) {}

  // 8. Reset parent AI status
  try {
    const socketService = require('../services/socketService');
    socketService.setConversationStatus(parentId, 'idle');
    if (rootConv.id !== parentId) {
      socketService.setConversationStatus(rootConv.id, 'idle');
    }
  } catch (_) {}

  console.log(`[sendReportToParent] Delivered focus report to parent ${parentId} (focus completed=${completed})`);

  return {
    delivered: true,
    parentConversationId: parentId,
    coordinatorSummary,
    sections: sections || null
  };
}

/**
 * Build a partial auto-report from the focus conversation's recent activity.
 * @param {Object} options
 * @param {Error} [options.error] - Optional error to include in the report summary.
 * @param {string} [options.reportReason] - Optional reason text prepended before error details.
 */
function buildPartialReport(db, conversationId, latestAssistantMessage, options = {}) {
  const { error, reportReason } = options;
  const messages = db.getMessagesByConversation(conversationId);
  const analyzedFiles = new Set();
  const modifiedFiles = new Set();

  for (const msg of messages) {
    if (msg.role === 'tool' && msg.tool_name) {
      let args = {};
      try {
        args = typeof msg.tool_args === 'string' ? JSON.parse(msg.tool_args) : (msg.tool_args || {});
      } catch (_) {
        args = {};
      }

      if (['readFile', 'readFileChunk', 'listFiles', 'readMultipleFiles', 'searchInFiles'].includes(msg.tool_name)) {
        const path = args.relativePath || args.path || args.filePath || args.file;
        if (path) analyzedFiles.add(path);
      }
      if (['writeFile', 'editFile', 'applyPatch'].includes(msg.tool_name)) {
        const path = args.relativePath || args.path || args.filePath || args.targetPath;
        if (path) modifiedFiles.add(path);
      }
    }
  }

  const latestContent = latestAssistantMessage
    ? String(latestAssistantMessage.content || '').trim().substring(0, 2000)
    : '';

  const workItems = [];
  if (analyzedFiles.size > 0) {
    workItems.push(`- Read ${analyzedFiles.size} file(s): ${Array.from(analyzedFiles).map(f => `\`${f}\``).join(', ')}`);
  }
  if (modifiedFiles.size > 0) {
    workItems.push(`- Modified ${modifiedFiles.size} file(s): ${Array.from(modifiedFiles).map(f => `\`${f}\``).join(', ')}`);
  }
  if (workItems.length === 0) {
    workItems.push('- No tool activity captured before termination.');
  }

  const summaryParts = [];
  if (reportReason) summaryParts.push(reportReason);
  if (error) {
    summaryParts.push(`Unrecoverable error: ${error.message || String(error)}`);
    if (error.stack) {
      summaryParts.push(`Stack trace (truncated):\n${String(error.stack).substring(0, 800)}`);
    }
  }
  if (summaryParts.length === 0) {
    summaryParts.push('Auto-generated because the focus exceeded its iteration budget without submitting a report.');
  }

  if (latestContent) {
    summaryParts.push('Latest assistant output snapshot:\n' + formatBlockQuote(latestContent));
  }

  const structured = buildStructuredReport({
    summary: summaryParts.join('\n\n'),
    workPerformed: workItems.join('\n'),
    outstanding: '- Focus terminated automatically. Scope and blockers remain unresolved.',
    handoff: '- Review the outstanding items and decide whether to spawn a new focus or adjust scope.'
  }, {
    heading: '# Auto-Report: Focus',
    completed: false,
    autogenerated: true
  });

  return {
    ...structured,
    autogenerated: true,
    warnings: []
  };
}

function hasExistingFocusReport(db, conversationId) {
  const currentConv = db.getConversation(conversationId);
  return !!(currentConv && currentConv.focus_report);
}

/**
 * Verifica se a conversa corrente tem um focus filho ativo.
 * This prevents creating a new focus while a child focus has not yet reported.
 */
function hasActiveFocus(db, conversationId) {
  const conv = db.getConversation(conversationId);
  if (!conv) return false;
  if (!conv.active_focus_id) return false;
  const active = db.getConversation(conv.active_focus_id);
  if (!active) {
    db.clearActiveFocus(conversationId);
    return false;
  }
  if (active.focus_report) {
    // Stale reference, clean it up
    db.clearActiveFocus(conversationId);
    return false;
  }
  return active.parent_id === conversationId;
}

/**
 * Investigation Tools: investigate and submitFindings
 *
 * These tools enable the MAIN-FOCUS recursive investigation system.
 * - investigate: available to MAIN and FOCUS conversations (creates a read-only subbot)
 * - submitFindings: available only to FOCUS conversations
 */
function createFocusTools(conversationId) {
  const connection = new DatabaseConnection();
  const db = new DatabaseAPI(connection);

  return {
    investigate: {
      name: 'investigate',
      description: `Spin up an isolated, READ-ONLY investigation subbot for the next atomic step.

Use this when a blocking uncertainty, unknown, or isolated analysis must be resolved before you continue. Provide only the information required to start immediately.

The new subbot inherits the same worktree but runs read-only: it can read files and run commands in a read-only sandbox, but cannot modify the repository. It will deliver a structured report with sections: Summary, Work Performed, Outstanding / Risks, Handoff Notes.

Call \`investigate\` at most once per turn and only after confirming:
1) the goal is a single critical question or analysis step,
2) the expected result is a minimal, inspectable deliverable or concrete answer,
3) guardrails and context are sufficient for autonomous investigation.

All additional \`investigate\` calls in the same turn are discarded server-side.` ,
      parameters: {
        type: 'object',
        properties: {
          goal: {
            type: 'string',
            description: 'The atomic objective for this focus. One critical step only.'
          },
          context: {
            type: 'string',
            description: 'Minimal context needed so the executor can start immediately.'
          },
          expectedResult: {
            type: 'string',
            description: 'Describe the minimal deliverable that proves the focus is complete.'
          },
          firstStep: {
            type: 'string',
            description: 'Explicit description of the first critical action the executor must perform.'
          },
          minimumDeliverable: {
            type: 'string',
            description: 'Concrete artifact/output expected at completion. Defaults to expectedResult.'
          },
          guardrails: {
            type: 'string',
            description: 'Constraints or boundaries the focus must respect (e.g., files, scope, safety rules).'
          },
          title: {
            type: 'string',
            description: 'Optional short title for this focus (auto-generated if empty)',
          }
        },
        required: ['goal', 'context', 'expectedResult']
      },
      
      handler: async ({ goal, context, expectedResult, firstStep, minimumDeliverable, guardrails, title }) => {
        try {
          // Get the current conversation to inherit properties
          const currentConv = db.getConversationWithProject(conversationId);
          if (!currentConv) {
            return { error: 'Current conversation not found' };
          }

          // Check if this conversation already has an active focus
          if (hasActiveFocus(db, conversationId)) {
            const activeFocus = db.getActiveFocus(conversationId);
            return {
              error: `Cannot create new focus. There is already an active focus "${activeFocus?.title || '#'}" (id=${activeFocus?.id || '?'}) that has not yet reported. Wait for its report before creating a new one.`
            };
          }

          // Build focus goal JSON
          const trimmedGoal = typeof goal === 'string' ? goal.trim() : '';
          const trimmedContext = typeof context === 'string' ? context.trim() : '';
          const trimmedExpected = typeof expectedResult === 'string' ? expectedResult.trim() : '';
          const trimmedFirstStep = typeof firstStep === 'string' ? firstStep.trim() : '';
          const trimmedDeliverable = typeof minimumDeliverable === 'string' && minimumDeliverable.trim().length > 0
            ? minimumDeliverable.trim()
            : trimmedExpected;
          const trimmedGuardrails = typeof guardrails === 'string' && guardrails.trim().length > 0
            ? guardrails.trim()
            : 'Stay inside the defined scope, avoid unrelated files, do not change repository state beyond what is required for the minimal deliverable.';

          // Focus is an independent work unit: it receives its own
          // iteration budget (MAX_ITERATIONS) instead of inheriting the value
          // already decremented from the parent.
          const focusMaxIterations = getMaxIterations();

          const focusGoal = JSON.stringify({
            schemaVersion: '2.0',
            goal: trimmedGoal,
            context: trimmedContext,
            expectedResult: trimmedExpected,
            firstStep: trimmedFirstStep,
            minimumDeliverable: trimmedDeliverable,
            guardrails: trimmedGuardrails,
            parentConversationId: conversationId,
            initialMaxIterations: focusMaxIterations,
            created_at: new Date().toISOString()
          });

          // Generate a title if not provided
          const focusTitle = title || `Focus: ${goal.substring(0, 60)}${goal.length > 60 ? '...' : ''}`;

          // Create the focus conversation, inheriting worktree from parent and
          // using its own independent max_iterations budget.
          const focusConv = db.createFocusConversation({
            project_id: currentConv.project_id,
            parent_id: conversationId,
            title: focusTitle,
            focus_goal: focusGoal,
            worktree_path: currentConv.worktree_path,
            repo_root: currentConv.repo_root,
            git_branch: currentConv.git_branch,
            base_branch: currentConv.base_branch,
            provider_id: currentConv.provider_id,
            model: currentConv.model,
            max_iterations: focusMaxIterations
          });

          // Set active_focus_id on the parent conversation (marks it as blocked)
          db.setActiveFocus(conversationId, focusConv.id);

          // Also propagate active_focus_id up the chain to ALL ancestors,
          // so any ancestor can see it's blocked by a descendant focus
          let ancestorId = currentConv.parent_id;
          while (ancestorId) {
            const ancestor = db.getConversation(ancestorId);
            if (!ancestor) break;
            db.setActiveFocus(ancestor.id, focusConv.id);
            ancestorId = ancestor.parent_id;
          }

          // Create a brief system message (the full goal is stored in focus_goal
          // and will be injected into the system prompt by sendToAI)
          const kickoffSystemMessage = (() => {
            const sections = [
              '# Focus Kickoff',
              `**Objective**
${trimmedGoal || '(missing goal)'}`,
              '## First Critical Step',
              trimmedFirstStep || 'Identify the very first actionable step. If unclear, request clarification from the parent before proceeding.',
              '## Minimal Deliverable',
              trimmedDeliverable || trimmedExpected || '(define the minimal deliverable before executing)',
              '## Guardrails',
              trimmedGuardrails,
              '## Context',
              trimmedContext || '(no additional context provided — rely on conversation history only)'
            ];
            return sections.join('\n\n');
          })();

          // Create initial system message in the focus conversation via ConversationManager
          // stateChange handles: message creation, broadcast, processing_state, phase, and runTurn
          // The phase is NOT set here — stateChange will infer it from conversation_type 'focus'
          // and transition from 'initial' to 'active' on first AI response.
          try {
            const serviceFactory = require('../services/serviceFactory');
            const cm = serviceFactory.getConversationManager();
            cm.stateChange(focusConv, {
              conversation_id: focusConv.id,
              role: 'user',
              content: kickoffSystemMessage,
              status: 'completed'
              // phase deliberately omitted — stateChange handles initial→active transition
            });
          } catch (e) {
            console.error('[FocusTools] Failed to create focus kickoff message via stateChange:', e);
            // Fallback: direct DB call if stateChange fails
            db.createMessage({
              conversation_id: focusConv.id,
              role: 'user',
              content: kickoffSystemMessage,
              status: 'completed'
            });
            db.markConversationAsQueued(focusConv.id);
            // Fallback also uses 'initial' phase so stateChange can transition correctly
            db.updateProcessingStateAndPhase(focusConv.id, 'queued', 'initial');
          }

          // Emit focus_started event via socket
          try {
            const socketService = require('../services/socketService');
            socketService.broadcastToConversation(conversationId, 'focus_started', {
              focusId: focusConv.id,
              parentConversationId: conversationId,
              goal: trimmedGoal.substring(0, 200),
              title: focusTitle,
              status: 'running',
              firstStep: trimmedFirstStep,
              minimumDeliverable: trimmedDeliverable,
              guardrails: trimmedGuardrails,
              context: trimmedContext
            });
          } catch (_) {}

          return {
            focusId: focusConv.id,
            status: 'started',
            title: focusTitle,
            message: `Focus "${focusTitle}" created and started. It will report back when done.`
          };
        } catch (error) {
          console.error('[FocusTools] investigate error:', error);
          return { error: `Failed to create focus: ${error.message}` };
        }
      }
    },

    submitFindings: {
      name: 'submitFindings',
      description: `Deliver the mandatory findings report to the parent conversation.

Use this once you have finished the assigned investigation or reached a stopping point.

The \`report\` string must contain the sections (in order): Summary, Work Performed, Outstanding / Risks, Handoff Notes. Describe concrete actions, evidence, and remaining issues. Set \`completed=true\` only when the expected result defined in the goal is fully satisfied.

This call always ends the investigation turn. Do not send additional tool calls afterwards.`,
      parameters: {
        type: 'object',
        properties: {
          report: {
            type: 'string',
            description: 'A markdown report describing what was done, files analyzed, decisions, results found, and remaining work.'
          },
          completed: {
            type: 'boolean',
            description: 'Whether the goal was fully completed. Defaults to true.'
          }
        },
        required: ['report']
      },
      handler: async ({ report, completed = true }) => {
        try {
          if (typeof report !== 'string') {
            return { error: 'submitFindings requires a markdown string as the `report` parameter.' };
          }

          const currentConv = db.getConversation(conversationId);
          if (!currentConv) {
            return { error: 'Focus conversation not found' };
          }

          if (currentConv.conversation_type !== 'focus') {
            return { error: 'submitFindings can only be called from a focus conversation' };
          }

          if (currentConv.focus_report) {
            console.log(`[FocusTools] submitFindings ignored for focus ${conversationId}: report already exists`);
            return { error: 'Findings report already sent. Investigation has terminated.' };
          }

          const parentId = currentConv.parent_id;
          if (!parentId) {
            return { error: 'Focus has no parent conversation' };
          }

          let focusGoal = {};
          try {
            focusGoal = currentConv.focus_goal ? JSON.parse(currentConv.focus_goal) : {};
          } catch (_) {
            focusGoal = {};
          }

          const normalizedReport = normalizeFocusReport(report, {
            focusGoal,
            completed,
            heading: `# Focus Report — ${currentConv.title}`
          });

          const result = await sendReportToParent({
            conversationId,
            report: normalizedReport.markdown,
            sections: normalizedReport.sections,
            completed,
            autogenerated: false,
            db,
            warnings: normalizedReport.warnings || []
          });

          return {
            delivered: result.delivered,
            parentConversationId: result.parentConversationId,
            message: result.error || 'Report delivered to parent conversation.',
            warnings: normalizedReport.warnings || []
          };
        } catch (error) {
          console.error('[FocusTools] submitFindings error:', error);
          return { error: `Failed to send focus report: ${error.message}` };
        }
      }
    }
  };
}

module.exports = {
  createFocusTools,
  sendReportToParent,
  buildPartialReport,
  hasExistingFocusReport,
  normalizeFocusReport,
  buildCoordinatorSummary,
};
